apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service-pizza-center
  name: service-pizza-center
spec:
  ports:
  - port: 2000
    protocol: TCP
    targetPort: 8080
  selector:
    app: pizza-center-api
  type: LoadBalancer
status:
  loadBalancer: {}
